### PR TITLE
potted tree

### PR DESCRIPTION
**Pull request by AagyaMishra**
Screenshot 2024-09-08 at 8 58 26 am

### CODE REVIEW

**Comment by AagyaMishra** [comment]
Screenshot 2024-09-08 at 9 58 02 am

**Comment by jdlowden** [comment]
Thanks Aagya. Mind converting them to FBX format (File / Export / FBX) and putting them in the correct location (Assets / Models)?

**Comment by DennisPYu** [comment]
Like Jonathan said, covert them to FBX format, and delete unnecessary files, make it tide and clean. The plants are more like sidewalk tree so if the model is for the outside, you may need to remove the pot under it. But if the plants you made is for inside the building, good work.

**Comment by AagyaMishra** [comment]
Done. Please take a quick look.

**Pull request merged**
