### PR TITLE
Dennis yu

### PR DESCRIPTION
**Pull request by DennisPYu**
Add a feature that the player will teleport from the **City** scene to the **Garage** scene.

### CODE REVIEW

**Review by jdlowden — CHANGES_REQUESTED** [review]
What is the need for this script? The garage scene doesn't use the player prefab and instead uses a VR interaction directly.

**Review by jdlowden — CHANGES_REQUESTED** [review]
Please remove the Materials from the Assets/Models/Simple Garage folder. These are not already imported in the Assets/Materials folder.

**Comment by DennisPYu** [comment]
I have updated as requested.

**Review by jdlowden — APPROVED** [review]
Looks good

**Pull request merged**
